name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release? yes/no'
        default: 'no'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache Gradle
      uses: actions/cache@v2
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-${{ hashFiles('gradle') }}
    - name: Build
      run: ./gradlew build
    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: build/reports/tests
    - name: Get publish token
      id: publish-token
      if: github.event.inputs.release == 'yes'
      uses: atlassian-labs/artifact-publish-token@v1.0.1
    - name: Release
      if: github.event.inputs.release == 'yes'
      env:
        atlassian_private_username: ${{ steps.publish-token.outputs.artifactoryUsername }}
        atlassian_private_password: ${{ steps.publish-token.outputs.artifactoryApiKey }}
      run: |
        ./gradlew release -Prelease.customUsername=${{ secrets.REPOSITORY_ACCESS_TOKEN }}
        ./gradlew publish
